andreaswolf/fractor

- fractor-xml/src/ValueObjectFactory/DomDocumentFactory.php
- fractor-xml/src/XmlFileProcessor.php
- fractor/composer.json
- fractor/config/application.php
- fractor/src/Application/FractorRunner.php
- fractor/src/Application/ValueObject/File.php
- fractor/src/Console/Contract/Output.php
- fractor/src/Console/Output/NullOutput.php
- fractor/src/Console/Output/SymfonyConsoleOutput.php
- fractor/src/Differ/ConsoleDiffer.php
- fractor/src/Differ/Contract/Differ.php
- fractor/src/Differ/DefaultDiffer.php
- fractor/src/Differ/Formatter/ColorConsoleDiffFormatter.php
- fractor/src/Differ/ValueObject/Diff.php
- fractor/src/Differ/ValueObject/FileDiff.php
- fractor/src/Differ/ValueObjectFactory/FileDiffFactory.php
- fractor/tests/Differ/Formatter/ColorConsoleDiffFormatter/ColorConsoleDiffFormatterTest.php
- fractor/tests/Differ/Formatter/ColorConsoleDiffFormatter/Fixture/expected_with_full_diff_by_phpunit.diff
- fractor/tests/Differ/Formatter/ColorConsoleDiffFormatter/Fixture/with_full_diff_by_phpunit.diff
- fractor/tests/Differ/Formatter/ColorConsoleDiffFormatter/Source/expected/expected.txt
- fractor/tests/Differ/Formatter/ColorConsoleDiffFormatter/Source/expected/expected_old_new.txt
> [TASK] Prepare Differ

- .github/workflows/publish.yml
> Add workflow for readonly splits

- fractor/src/Reporting/ChangelogExtractor.php
- fractor/tests/Reporting/ChangelogExtractor/ChangelogExtractorTest.php
- fractor/tests/Reporting/ChangelogExtractor/Fixture/RuleWithChangelog.php
- fractor/tests/Reporting/ChangelogExtractor/Fixture/RuleWithNoChangelog.php
- typo3-fractor/rules/TYPO3v7/FlexForm/AddRenderTypeToFlexFormFractor.php
> [FEATURE] Add ChangelogExtractor for Reporting

- .github/workflows/lint_test_pull_requests.yaml
- README.md
- fractor-yaml/.gitignore
- fractor-yaml/composer.json
- fractor-yaml/config/application.php
- fractor-yaml/ecs.php
- fractor-yaml/phpstan.neon
- fractor-yaml/phpunit.xml
- fractor-yaml/rector.php
- fractor-yaml/src/Contract/YamlDumper.php
- fractor-yaml/src/Contract/YamlFractorRule.php
- fractor-yaml/src/Contract/YamlParser.php
- fractor-yaml/src/Exception/ParseException.php
- fractor-yaml/src/SymfonyYamlDumper.php
- fractor-yaml/src/SymfonyYamlParser.php
- fractor-yaml/src/YamlFileProcessor.php
- fractor-yaml/tests/Fixtures/DummyYamlFractorRule.php
- fractor-yaml/tests/YamlFileProcessor/Fixtures/fixture.yaml
- fractor-yaml/tests/YamlFileProcessor/YamlFileProcessorTest.php
- fractor-yaml/tests/YamlFileProcessor/config/config.php
> [FEATURE] Fractor for Yaml files

- .github/workflows/docs.yaml
> [TASK] Generate docs

- .github/workflows/docs.yaml
> [TASK] Create branch to generate docs

- fractor/src/Application/FractorRunner.php
- fractor/src/Console/Contract/Output.php
- fractor/src/Console/Output/NullOutput.php
- fractor/src/Console/Output/SymfonyConsoleOutput.php
- fractor/src/Reporting/FractorsChangelogLinesResolver.php
- fractor/src/Reporting/FractorsChangelogResolver.php
- fractor/tests/Fixture/DummyProcessor/Rules/ReplaceXXXTextRule.php
- fractor/tests/Reporting/FractorsChangelogLinesResolver/FractorsChangelogLinesResolverTest.php
- fractor/tests/Reporting/FractorsChangelogResolver/FractorsChangelogResolverTest.php
> [FEATURE] Output applied rules in console

- extension-installer/.gitattributes
- extension-installer/README.md
- fractor-doc-generator/.gitattributes
- fractor-xml/.gitattributes
- fractor-yaml/.gitattributes
- fractor/.gitattributes
- typo3-fractor/.gitattributes
> [TASK] Add .gitattributes to packages

- fractor-fluid/tests/FluidFileProcessor/FluidFileProcessorTest.php
- fractor-fluid/tests/FluidFileProcessor/config/fractor.php
- fractor-yaml/tests/YamlFileProcessor/config/config.php
- fractor-yaml/tests/YamlFileProcessor/config/fractor.php
- typo3-fractor/rules/TYPO3v10/Fluid/RemoveNoCacheHashAndUseCacheHashAttributeFractor.php
- typo3-fractor/rules/TYPO3v10/Yaml/TranslationFileFractor.php
- typo3-fractor/tests/Rules/TYPO3v10/Fluid/Fixtures/fixture.html
- typo3-fractor/tests/Rules/TYPO3v10/Fluid/RemoveNoCacheHashAndUseCacheHashAttributeFractorTest.php
- typo3-fractor/tests/Rules/TYPO3v10/Fluid/config/config.php
- typo3-fractor/tests/Rules/TYPO3v10/Fluid/config/fractor.php
- typo3-fractor/tests/Rules/TYPO3v10/Yaml/EmailFinisherFractor/EmailFinisherFractorTest.php
- typo3-fractor/tests/Rules/TYPO3v10/Yaml/TranslationFileFractor/TranslationFileFractorTest.php
> [FEATURE] Add RemoveNoCacheHashAndUseCacheHashAttributeFractor

- fractor-xml/composer.json
- fractor-xml/src/AbstractXmlFractor.php
- fractor-xml/src/Contract/DomNodeVisitor.php
- fractor-xml/src/DomDocumentIterator.php
- fractor-xml/src/XmlFileProcessor.php
- fractor-xml/tests/AbstractXmlFractorTest.php
- fractor-xml/tests/DomDocumentIteratorTest.php
- fractor-xml/tests/Fixtures/CollectingDomNodeVisitor.php
- typo3-fractor/rules/TYPO3v7/FlexForm/AddRenderTypeToFlexFormFractor.php
> Record applied rules in AbstractXmlRector

- fractor-fluid/config/application.php
- fractor-fluid/src/FluidFileProcessor.php
- fractor-xml/composer.json
- fractor-xml/config/application.php
- fractor-xml/src/DomDocumentIterator.php
- fractor-xml/src/XmlFileProcessor.php
- fractor-yaml/config/application.php
- fractor-yaml/src/YamlFileProcessor.php
- fractor/config/application.php
- fractor/src/Application/RuleSkipper.php
- fractor/src/Rules/RulesProvider.php
- fractor/tests/Application/FractorRunner/config/config.php
- fractor/tests/Application/RuleSkipper/Fixture/RuleA.php
- fractor/tests/Application/RuleSkipper/Fixture/RuleB.php
- fractor/tests/Application/RuleSkipper/RuleSkipperTest.php
- fractor/tests/Configuration/AllowedFileExtensionsResolver/config/config.php
- fractor/tests/Fixture/DummyProcessor/FileProcessor/TextFileProcessor.php
- fractor/tests/Rules/RulesProviderTest.php
> Skip rules by configuration

- fractor/src/Configuration/ValueObject/Configuration.php
> [TASK] Add comment for configuration class

- typo3-fractor/rules/TYPO3v12/Fluid/AbstractMessageGetSeverityFluidRector.php
- typo3-fractor/tests/Rules/TYPO3v12/Fluid/AbstractMessageGetSeverityFluidRector/AbstractMessageGetSeverityFluidRectorTest.php
- typo3-fractor/tests/Rules/TYPO3v12/Fluid/AbstractMessageGetSeverityFluidRector/Fixtures/fixture.html
- typo3-fractor/tests/Rules/TYPO3v12/Fluid/AbstractMessageGetSeverityFluidRector/config/config.php
- typo3-fractor/tests/Rules/TYPO3v12/Fluid/AbstractMessageGetSeverityFluidRector/config/fractor.php
> [FEATURE] Add AbstractMessageGetSeverityFluidRector

- fractor-composer-json/rules/AddPackageToRequireDevComposerJsonFractorRule.php
- fractor-composer-json/rules/ChangePackageVersionComposerJsonFractorRule.php
- fractor-composer-json/rules/RemovePackageComposerJsonFractorRule.php
- fractor-composer-json/rules/RenamePackageComposerJsonFractorRule.php
- fractor-composer-json/rules/ReplacePackageAndVersionComposerJsonFractorRule.php
- fractor-composer-json/src/Contract/ComposerJson.php
- fractor-composer-json/src/ValueObject/EtaOrionisComposerJson.php
- fractor-composer-json/src/ValueObject/RenamePackage.php
- fractor-composer-json/src/ValueObject/ReplacePackageAndVersion.php
- fractor-composer-json/tests/AddPackageToRequireComposerJsonFractorRule/AddPackageToRequireComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/AddPackageToRequireDevComposerJsonFractorRule/AddPackageToRequireDevComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/AddPackageToRequireDevComposerJsonFractorRule/Fixtures/composer.json
- fractor-composer-json/tests/AddPackageToRequireDevComposerJsonFractorRule/config/config.php
- fractor-composer-json/tests/AddPackageToRequireDevComposerJsonFractorRule/config/fractor.php
- fractor-composer-json/tests/ChangePackageVersionComposerJsonFractorRule/ChangePackageVersionComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/ChangePackageVersionComposerJsonFractorRule/Fixtures/composer.json
- fractor-composer-json/tests/ChangePackageVersionComposerJsonFractorRule/config/config.php
- fractor-composer-json/tests/ChangePackageVersionComposerJsonFractorRule/config/fractor.php
- fractor-composer-json/tests/RemovePackageComposerJsonFractorRule/Fixtures/composer.json
- fractor-composer-json/tests/RemovePackageComposerJsonFractorRule/RemovePackageComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/RemovePackageComposerJsonFractorRule/config/config.php
- fractor-composer-json/tests/RemovePackageComposerJsonFractorRule/config/fractor.php
- fractor-composer-json/tests/RenamePackageComposerJsonFractorRule/Fixtures/composer.json
- fractor-composer-json/tests/RenamePackageComposerJsonFractorRule/RenamePackageComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/RenamePackageComposerJsonFractorRule/config/config.php
- fractor-composer-json/tests/RenamePackageComposerJsonFractorRule/config/fractor.php
- fractor-composer-json/tests/ReplacePackageAndVersionComposerJsonFractorRule/Fixtures/composer.json
- fractor-composer-json/tests/ReplacePackageAndVersionComposerJsonFractorRule/ReplacePackageAndVersionComposerJsonFractorRuleTest.php
- fractor-composer-json/tests/ReplacePackageAndVersionComposerJsonFractorRule/config/config.php
- fractor-composer-json/tests/ReplacePackageAndVersionComposerJsonFractorRule/config/fractor.php
> [FEATURE] Add more rules

- extension-installer/LICENSE
- fractor-doc-generator/LICENSE
- fractor-fluid/LICENSE
- fractor-xml/LICENSE
- fractor-yaml/LICENSE
- fractor/LICENSE
- typo3-fractor/LICENSE
> [TASK] Add LICENSE file

- README.md
- packages/fractor-composer-json/README.md
- packages/fractor-composer-json/docs/composer-json-fractor-rules.md
- packages/fractor-fluid/README.md
- packages/fractor-xml/README.md
- packages/fractor-yaml/README.md
> [TASK] Add README.md for other packages

- README.md
> [TASK] Describe dry-run in README.md

- composer.json
- packages/fractor-fluid/composer.json
- packages/fractor-xml/composer.json
- packages/fractor-yaml/composer.json
- packages/fractor/composer.json
This package doesn't need to be included in a release
> [TASK] Make symplify/rule-doc-generator-contracts a dev dependency

- composer.json
- packages/fractor-doc-generator/composer.json
- packages/fractor-yaml/composer.json
- packages/fractor/composer.json
> [TASK] Adjust requirements for Symfony components

- README.md
> [BUGFIX] Fix missing use statement in README.md example

- packages/fractor/src/Application/FractorRunner.php
> Only advance progress once per file

- README.md
- packages/extension-installer/README.md
- packages/fractor-composer-json/README.md
- packages/fractor-doc-generator/README.md
- packages/fractor-fluid/README.md
- packages/fractor-phpstan-rules/README.md
- packages/fractor-typoscript/README.md
- packages/fractor-xml/README.md
- packages/fractor-yaml/README.md
- packages/fractor/README.md
- packages/typo3-fractor/README.md
This includes a "development" section in all READMEs, adds a README to a9f/fractor, and improves wording and formatting of the READMEs across the board.
Resolves: #201
> Ensure all packages have a README, improve READMEs

- packages/fractor-xml/src/DomDocumentIterator.php
This commit will also improve the error message.
Fixes: #250
> [BUGFIX] Only check for parentNode if modifications need to be done

- composer.json
- packages/fractor-composer-json/src/ComposerJsonFileProcessor.php
- packages/fractor-fluid/src/FluidFileProcessor.php
- packages/fractor-typoscript/src/TypoScriptFileProcessor.php
- packages/fractor-xml/src/XmlFileProcessor.php
- packages/fractor-yaml/src/YamlFileProcessor.php
- packages/fractor/composer.json
- packages/fractor/config/application.php
- packages/fractor/src/Application/FractorRunner.php
- packages/fractor/src/Caching/Cache.php
- packages/fractor/src/Caching/CacheFactory.php
- packages/fractor/src/Caching/Config/FileHashComputer.php
- packages/fractor/src/Caching/Contract/ValueObject/Storage/CacheStorageInterface.php
- packages/fractor/src/Caching/Detector/ChangedFilesDetector.php
- packages/fractor/src/Caching/Enum/CacheKey.php
- packages/fractor/src/Caching/UnchangedFilesFilter.php
- packages/fractor/src/Caching/ValueObject/CacheFilePaths.php
- packages/fractor/src/Caching/ValueObject/CacheItem.php
- packages/fractor/src/Caching/ValueObject/Storage/FileCacheStorage.php
- packages/fractor/src/Caching/ValueObject/Storage/MemoryCacheStorage.php
- packages/fractor/src/Configuration/FractorConfigurationBuilder.php
- packages/fractor/src/Configuration/Option.php
- packages/fractor/src/Configuration/Parameter/SimpleParameterProvider.php
- packages/fractor/src/Console/Application/FractorApplication.php
- packages/fractor/src/Console/Command/ProcessCommand.php
- packages/fractor/src/Exception/Cache/CachingException.php
- packages/fractor/src/FileSystem/FilesFinder.php
- packages/fractor/src/Helper/FileHasher.php
- rector.php
> [FEATURE] Provide a cache for unchanged files

- composer.json
- packages/fractor-xml/composer.json
> [FEATURE] Update pretty-xml that fixes issues

- README.md
- e2e/typo3-typoscript/fractor.php
- e2e/typo3-yaml/fractor.php
- packages/fractor-typoscript/tests/TypoScriptStatementsIterator/config/fractor.php
- packages/typo3-fractor/README.md
- packages/typo3-fractor/config/level/up-to-typo3-14.php
- packages/typo3-fractor/config/typo3-14.php
- packages/typo3-fractor/docs/typo3-fractor-rules.md
- packages/typo3-fractor/rules-tests/TYPO3v14/TypoScript/RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractor/Fixtures/fixture.typoscript.fixture
- packages/typo3-fractor/rules-tests/TYPO3v14/TypoScript/RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractor/RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractorTest.php
- packages/typo3-fractor/rules-tests/TYPO3v14/TypoScript/RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractor/config/fractor.php
- packages/typo3-fractor/rules/TYPO3v14/TypoScript/RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractor.php
- packages/typo3-fractor/src/Set/Typo3LevelSetList.php
- packages/typo3-fractor/src/Set/Typo3SetList.php
Fixes: https://github.com/sabbelasichon/typo3-rector/issues/4490
> [FEATURE] Add RemoveExposeNonexistentUserInForgotPasswordDialogSettingInFeLoginFractor

- packages/typo3-fractor/config/typo3-11.php
- packages/typo3-fractor/docs/typo3-fractor-rules.md
- packages/typo3-fractor/rules-tests/TYPO3v11/TypoScript/RenameFeLoginSettingShowForgotPasswordLinkFractor/Fixtures/constant.typoscript.fixture
- packages/typo3-fractor/rules-tests/TYPO3v11/TypoScript/RenameFeLoginSettingShowForgotPasswordLinkFractor/Fixtures/fixture.typoscript.fixture
- packages/typo3-fractor/rules-tests/TYPO3v11/TypoScript/RenameFeLoginSettingShowForgotPasswordLinkFractor/RenameFeLoginSettingShowForgotPasswordLinkFractorTest.php
- packages/typo3-fractor/rules-tests/TYPO3v11/TypoScript/RenameFeLoginSettingShowForgotPasswordLinkFractor/config/fractor.php
- packages/typo3-fractor/rules/TYPO3v11/TypoScript/RenameFeLoginSettingShowForgotPasswordLinkFractor.php
Fixes: https://github.com/sabbelasichon/typo3-rector/issues/4268
> [FEATURE] Add RenameFeLoginSettingShowForgotPasswordLinkFractor

- phpunit.xml
Display details on tests that trigger:
- deprecations
- errors
- notices
- warnings
> [TASK] Display details on tests

- .editorconfig
- packages/fractor-xml/src/XmlFileProcessor.php
- packages/fractor-xml/tests/Fixtures/DummyXmlFractorRule.php
- packages/fractor-xml/tests/XmlFileProcessor/Fixtures/fixture.xml.fixture
- packages/fractor-xml/tests/XmlFileProcessor/XmlFileProcessorTest.php
- packages/fractor-xml/tests/XmlFileProcessor/config/fractor.php
> [BUGFIX] DOMDocument escapes arrows

- packages/fractor/src/FileSystem/FilesFinder.php
> [BUGFIX] Include dot files (.htaccess)

- packages/fractor-typoscript/src/TypoScriptFileProcessor.php
> [BUGFIX] Use filtered rules instead of all

- packages/fractor-htaccess/composer.json
> [TASK] Update tivie/htaccess-parser for PHP 8.4 compat
